### ISSUE TITLE
请教一下数据准备问题

### ISSUE THREAD

**Issue by lzghades** [Liang-yc/ssq#14]
ssq_data.py里的get_exl_data方法用来获取数据，想问下红色球的数字都减了1，蓝色球的数字加了32，这样是有什么特殊作用吗？

**Comment by Liang-yc** [comment]
这样做只是为了区分红号和蓝号。蓝号的数字和红号是重叠的，应该作为新的类别号，而不是和红号共用。你可以试一下不加32做实验，预测结果的蓝号会出现超过16的情况。

**Comment by lzghades** [comment]
> 这样做只是为了区分红号和蓝号。蓝号的数字和红号是重叠的，应该作为新的类别号，而不是和红号共用。你可以试一下不加32做实验，预测结果的蓝号会出现超过16的情况。

好的，多谢，我测试一下。
