### ISSUE TITLE
tf2分支ssq4all_v4.py在训练的时候使用CTRL+C取消训练, 无法保存结果, 

### ISSUE THREAD

**Issue by anzhe1989** [Liang-yc/ssq#26]
大佬,tf2分支,我没办法使用GPU训练,   只能使用效率低的CPU训练,  好不容易训练了5000次了,  ctrl+c取消训练后,  没有保存结果,  我再次训练的时候,还是从第一次开始训练

**Comment by Liang-yc** [comment]
你那个可能是保存路径不存在，导致文件没有保存下来，所以下一次只能从头开始。见`ssq4all_v4.py`line 17
`tf.compat.v1.app.flags.DEFINE_string('model_dir', './model4all_v4', 'model save path.')`

你把下面两句反注释掉就可以了：
```
# if not os.path.exists(FLAGS.model_dir):
#     os.makedirs(FLAGS.model_dir)
```

**Comment by anzhe1989** [comment]
谢谢大佬
