### ISSUE TITLE
怎么预测？

### ISSUE THREAD

**Issue by Sabirjan** [Liang-yc/ssq#4]
训练完了，怎么预测。
谢谢

**Comment by Sabirjan** [comment]
比如 ：我想训练 3D的数据 或者 35选 7的  怎么弄。。。
指导一下，谢谢

**Comment by Sabirjan** [comment]
创建群，感兴趣的进去一起分析啊

**Comment by Liang-yc** [comment]
1.关于预测：
用ssq.py训练的，用ssq_test.py预测；用ssq4all.py训练的，用ssq4all_test.py预测；
2.训练35选7：
看代码。

**Comment by pytomtoto** [comment]
> 1.关于预测：
> 用ssq.py训练的，用ssq_test.py预测；用ssq4all.py训练的，用ssq4all_test.py预测；
> 2.训练35选7：
> 看代码。

```
更新了ssq.xls数据，运行ssq_test.py 得到以下输出
input: [[ 4 10 11 14 15 29  5]]
output:[28 22 22 22  5  2 13]
input：上一期的双色球数字；
output：预测的下一期的数字。
为什么下一期有三个22号
```

**Comment by Liang-yc** [comment]
你没怎么训练，输出是乱的很正常。当然训练一段时间后还是不能避免有数字重复的情况。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: pytomtoto <notifications@github.com&gt;
发送时间: 2019年10月10日 14:17
收件人: Liang-yc/ssq <ssq@noreply.github.com&gt;
抄送: Liang-yc <1697205782@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[Liang-yc/ssq] 怎么预测？ (#4)



 
1.关于预测：
 用ssq.py训练的，用ssq_test.py预测；用ssq4all.py训练的，用ssq4all_test.py预测；
 2.训练35选7：
 看代码。
  更新了ssq.xls数据，运行ssq_test.py 得到以下输出 input: [[ 4 10 11 14 15 29  5]] output:[28 22 22 22  5  2 13] input：上一期的双色球数字； output：预测的下一期的数字。 为什么下一期有三个22号
