### ISSUE TITLE
训练到Epoch 149999 会停止

### ISSUE THREAD

**Issue by SkyBlueEternal** [Liang-yc/ssq#8]
训练到Epoch 149999 会停止，但是保存的进度为145000。请问下是不是有BUG

**Comment by Liang-yc** [comment]
你跑的应该是`ssq.py`，设定的`epochs=150000`, 原则上，因为149999%5000！=0，而且150000又不会达到，所以只保存了145000的结果。这个我之前忘记改，现在好了。

**Comment by SkyBlueEternal** [comment]
OK.解决了。
